// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase app (web only).
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgE_fc7jgJzYArSu-DHgMKVgs4yZD_F6g',
    appId: '1:844190609385:web:ce800c025f779652462578',
    messagingSenderId: '844190609385',
    projectId: 'aregenkibet',
    authDomain: 'aregenkibet.firebaseapp.com',
    storageBucket: 'aregenkibet.appspot.com',
    measurementId: 'G-LPCCRZS6ZN',
  );
}
